### ISSUE TITLE
Errors when trying to translate from Russian or Arabic

### ISSUE THREAD

**Issue by 13aal** [13aal/Translation-Center#1]
While trying to translate from Russian or Arabic you get the following errors:

For Russian:
      /usr/local/lib/ruby/1.9.1/syck.rb:145:in `initialize': No such file or directory - russian.yaml (Errno::ENOENT)
              from /usr/local/lib/ruby/1.9.1/syck.rb:145:in`open'
              from /usr/local/lib/ruby/1.9.1/syck.rb:145:in `load_file'
              from translator.rb:44:in`russian_translate'
              from translator.rb:17:in `welcome'
              from translator.rb:72:in`<main>'

For Arabic:
      /usr/local/lib/ruby/1.9.1/syck.rb:135:in `load': syntax error on line 7, col 0:`marhaban: welcome' (ArgumentError)
              from /usr/local/lib/ruby/1.9.1/syck.rb:135:in `load'
              from /usr/local/lib/ruby/1.9.1/syck.rb:146:in`block in load_file'
              from /usr/local/lib/ruby/1.9.1/syck.rb:145:in `open'
              from /usr/local/lib/ruby/1.9.1/syck.rb:145:in`load_file'
              from translator.rb:59:in `arabic_translate'
              from translator.rb:21:in`welcome'
              from translator.rb:72:in `<main>'

Issue may be that I'm on my work computer but all files are in the same location

**Comment by 13aal** [comment]
Russian is fixed Arabic is still returning the error:
    /usr/local/lib/ruby/1.9.1/syck.rb:135:in `load': syntax error on line 7, col 0:`marhaban: welcome'     (ArgumentError)
            from /usr/local/lib/ruby/1.9.1/syck.rb:135:in `load'
            from /usr/local/lib/ruby/1.9.1/syck.rb:146:in`block in load_file'
            from /usr/local/lib/ruby/1.9.1/syck.rb:145:in `open'
            from /usr/local/lib/ruby/1.9.1/syck.rb:145:in`load_file'
            from translator.rb:59:in `arabic_translate'
            from translator.rb:21:in`welcome'
            from translator.rb:72:in `<main>'

**Comment by 13aal** [comment]
Issue has been fixed, replaced Arabic yaml file with one that's Arabic wording was correct.
